[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Documentos Electronicos"
authors = [{name = "jhon barranco", email = "jbarrancoandrade@gmail.com"}]
dynamic = ["version", "description"]
